// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknhuIMJ-lAHtBVfkBgWwdA1RvbCjhElo',
    appId: '1:770620836493:web:8c6a170697d22834a2b0c4',
    messagingSenderId: '770620836493',
    projectId: 'hireplus-4350a',
    authDomain: 'hireplus-4350a.firebaseapp.com',
    storageBucket: 'hireplus-4350a.appspot.com',
    measurementId: 'G-M6PXWXBZRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehpxVf0c1LueQZaOYJycAKYq7uI7LcZM',
    appId: '1:770620836493:android:3e4bc25f14dfde48a2b0c4',
    messagingSenderId: '770620836493',
    projectId: 'hireplus-4350a',
    storageBucket: 'hireplus-4350a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgmtBa-wUCw3TaAiVxVGt0ymEkvJUpn8',
    appId: '1:770620836493:ios:d210cf1b88db7d01a2b0c4',
    messagingSenderId: '770620836493',
    projectId: 'hireplus-4350a',
    storageBucket: 'hireplus-4350a.appspot.com',
    iosBundleId: 'com.example.hireplus',
  );
}
